select * from customer limit 20;
--1. what is the total revenue generated by the male vs female?
select gender, sum(purchase_amoun) 
from customer
group by gender;

--2. which customer used discount but still spent more thatn the averagepurchase amount?
select customer_id, purchase_amoun from customer
where discount_applied = 'Yes' and purchase_amoun > (select avg(purchase_amoun) from customer);

--3. which are the top 5 products with highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "avg_review_rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--4. Compare the average purchase amounts between standard and express shipping?
select shipping_type, round(sum(purchase_amoun),2) from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--5. Do subscribed customer spend more? Compare average spend and total revenue between 
--subscriber and non subscriber?
select subscription_status, count(customer_id) as total_id, round(avg(purchase_amoun),2) as avg_spent, round(sum(purchase_amoun),2) as total_revenue
from customer
where subscription_status in ('Yes', 'No')
group by subscription_status
order by total_revenue, avg_spent desc;

--6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased, 
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 END)/count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7.Segment customers into new returning and loyal best on their totoalnumber of previous 
--purchase, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
from customer
)
select customer_segment, count(*) as count_of_segment from customer_type
group by customer_segment;


--8. What are the top 3 most purchased products within each category?

with item_counts as (
select category, item_purchased,count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank 
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_counts
where item_rank<=3;

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to 
--subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status;

-- 10. What is the revenue contribution by each age group?
select age_group, sum(purchase_amoun) as revenue_contribution from customer
group by age_group
order by revenue_contribution desc;
